services:
  httpd_serve:
    container_name: httpd_serve
    build: 
      args:
        user: serve
        uid: 1000
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:80
    depends_on:
      - php84_fpm
    networks:
      - my_network
    volumes:
      - ~/Documents/WEB/docker_apps:/var/www
  php73_fpm:
    container_name: php73_fpm
    build: 
      args:
        user: serve
        uid: 1000
      context: ../images/php_7.3fpm/.
      dockerfile: Dockerfile
    ports:
      - 7373:80
    networks:
      - my_network
    volumes:
      - ~/Documents/WEB/docker_apps:/var/www
  php84_fpm:
    container_name: php84_fpm
    build: 
      args:
        user: serve
        uid: 1000
      context: ../images/php_8.4fpm/.
      dockerfile: Dockerfile
    ports:
      - 8484:80
    volumes:
      - ~/Documents/WEB/docker_apps:/var/www
    networks:
      - my_network
  phpmyadmin:
    image: phpmyadmin:5.2.2
    ports:
      - 8082:80
    restart: always
    networks:
      - my_network
    environment:
      - PMA_HOST=mysql5
    depends_on:
      - mysql5
  mysql5:
    container_name: mysql5
    image: mysql:5.6.51
    ports:
      - "3308:3306"
    environment:
      MYSQL_USER: "db_user"
      MYSQL_DATABASE: "demo_sf7"
      MYSQL_PASSWORD: "123456+"
      MYSQL_ROOT_PASSWORD: "123456+"
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
    volumes:
      - ~/Documents/WEB/docker_apps/data/images/mysql:/var/lib/mysql # /home/mysql/mysql5/data
    networks:
      - my_network
  mailpit:
    image: axllent/mailpit
    container_name: mailpit
    restart: unless-stopped
    volumes:
      - ./data:/data
    ports:
      - 8025:8025
      - 1025:1025
    environment:
      MP_MAX_MESSAGES: 5000
      MP_DATABASE: /data/mailpit.db
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
    networks:
      - my_network
networks:
  my_network:
    driver: bridge
