services:
  httpd_serve:
    container_name: httpd_serve
    build: 
      args:
        user: serve
        uid: 1000
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:80
    depends_on:
      - php73_fpm
    networks:
      - my_network
    volumes:
      - ~/Documents/WEB/docker_apps:/var/www
  php73_fpm:
    container_name: php73_fpm
    build: 
      args:
        user: serve
        uid: 1000
      context: ../images/php_7.3fpm/.
      dockerfile: Dockerfile
    ports:
      - 7373:80
    networks:
      - my_network
    volumes:
      - ~/Documents/WEB/docker_apps:/var/www
  mysql5:
    container_name: mysql5
    image: mysql:5.6.51
    ports:
      - 3308:3308
    networks:
      - my_network
    environment:
      MYSQL_ROOT_HOST: 127.0.0.1
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
      MYSQL_DATABASE: db_debian_apps
      MYSQL_ROOT_PASSWORD: 123456+
      MYSQL_USER: db_user
      MYSQL_PASSWORD: 123456+
    volumes:
      - ~/Documents/WEB/docker_apps/data/images/mysql:/var/lib/mysql # /home/mysql/mysql5/data
  phpmyadmin:
    image: phpmyadmin:5.2.2
    ports:
      - 8082:80
    links:
      - mysql5
    networks:
      - my_network
    environment:
      - PMA_ARBITRARY=1
    restart: always
networks:
  my_network:
    driver: bridge
